# Generated by Django 3.2.7 on 2021-09-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_auto_20210925_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriaproducto',
            old_name='foto',
            new_name='imagen',
        ),
    ]
